test_current:
  stage: test
  tags:
  - matlab
  script:
  - matlab -nodisplay -r Test.DRIVE_CI

test_2017b:
  stage: test
  tags:
  - matlab
  script:
  - export PATH="/opt/MATLAB/R2017b/bin:$PATH"
  - matlab -nodisplay -r Test.DRIVE_CI
